name: GitHub Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install backslide
      run: yarn add backslide@2.3.7
    - name: Build dist
      run: ./node_modules/.bin/bs export
    - name: Fix file:// rename
      run: sed -i "s?file://$(pwd)/??g" dist/presentation.html
    - name: rename index.html
      run: mv ./dist/presentation.html ./dist/index.html
    - name: Build pdf
      run: ./node_modules/.bin/bs pdf
    - name: Move pdf to dist
      run: mv ./pdf/presentation.pdf ./dist/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
  
